name: 🔒 Security Vulnerability
description: Report a security vulnerability (Please use private reporting for critical issues)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please use GitHub's private vulnerability reporting feature or contact us directly at security@yetify.ai
        
        This template is for non-critical security improvements and general security concerns.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      description: Please confirm your understanding
      options:
        - label: I understand this is for non-critical security issues only
          required: true
        - label: I have not included sensitive information in this public report
          required: true
        - label: I have considered the responsible disclosure process
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (Security improvement, no immediate risk)
        - Medium (Potential security weakness)
        - High (Exploitable vulnerability - consider private reporting)
        - Critical (Immediate threat - USE PRIVATE REPORTING)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - Cryptography
        - Smart Contract Security
        - API Security
        - Data Protection
        - Infrastructure Security
        - Dependency Vulnerabilities
        - Privacy Concerns
        - Code Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of Yetify is affected?
      options:
        - Frontend (Next.js)
        - Backend API
        - Smart Contracts
        - AI Strategy Engine
        - Execution Engine
        - Database
        - Authentication System
        - Wallet Integration
        - External APIs
        - Infrastructure
        - Dependencies
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern (avoid sensitive details)
      placeholder: |
        Provide a general description of the security issue without revealing
        specific exploitation details that could be harmful if public.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this issue is exploited?
      placeholder: |
        Describe the potential impact:
        - Data exposure
        - Unauthorized access
        - Financial loss
        - System compromise
        - Privacy violation
    validations:
      required: true

  - type: textarea
    id: affected-users
    attributes:
      label: Affected Users
      description: Who could be impacted by this security issue?
      placeholder: |
        - All users
        - Users with specific roles
        - Admin users only
        - External integrators
        - Specific user scenarios
    validations:
      required: true

  - type: dropdown
    id: blockchain-risk
    attributes:
      label: Blockchain/Smart Contract Risk
      description: Does this involve blockchain or smart contract security?
      options:
        - "No blockchain involvement"
        - "Smart contract vulnerability"
        - "Transaction security"
        - "Private key handling"
        - "Cross-chain security"
        - "Protocol integration risk"
    validations:
      required: false

  - type: textarea
    id: reproduction-hint
    attributes:
      label: General Reproduction Information
      description: General steps that demonstrate the issue (avoid specific exploits)
      placeholder: |
        Provide general steps that show the security concern exists,
        but avoid detailed exploitation instructions.
    validations:
      required: false

  - type: textarea
    id: recommendation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for addressing this issue?
      placeholder: |
        - Input validation improvements
        - Authentication enhancements
        - Access control changes
        - Code review recommendations
        - Security best practices

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Where have you observed this issue?
      options:
        - label: Local development
        - label: Staging environment
        - label: Production environment
        - label: Testnet
        - label: Mainnet
        - label: Documentation/Code review

  - type: input
    id: cve
    attributes:
      label: Related CVE/Advisory
      description: Any related CVE numbers or security advisories?
      placeholder: "CVE-2023-XXXXX or advisory URL"

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to security best practices, similar issues, or documentation
      placeholder: |
        - OWASP guidelines
        - Security research papers
        - Similar vulnerabilities in other projects
        - Relevant security documentation

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Responsible disclosure commitment
      options:
        - label: I commit to responsible disclosure practices
          required: true
        - label: I will not publicly disclose details until resolution
          required: true
        - label: I understand the security team will provide updates on timeline
          required: true

  - type: markdown
    attributes:
      value: |
        ## Security Contact Information
        
        For critical security vulnerabilities that require immediate attention:
        - Use GitHub's private vulnerability reporting
        - Email: security@yetify.ai
        - Include "URGENT SECURITY" in the subject line
        
        Thank you for helping keep Yetify secure! 🛡️
